#!/usr/bin/env python3
"""Write kernel/apps/shell/cryptotest_vectors.inc: fixed signatures that the
kernel's `cryptotest` command must accept (and reject once tampered with).

The keys and signatures come from tests/crypto_ref.py with a fixed seed, so
running this again produces the same file. Only needed when adding vectors.

    python tools/gen_cryptotest.py
"""

from __future__ import annotations

import hashlib
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from tests import crypto_ref as ref  # noqa: E402

OUT = ROOT / "kernel" / "apps" / "shell" / "cryptotest_vectors.inc"
MESSAGE = b"Antigravity OS signature test vector"


def _db(label: str, data: bytes) -> str:
    lines = [f"{label}:"]
    for i in range(0, len(data), 16):
        lines.append("    db " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]))
    lines.append(f"{label}_len equ $ - {label}")
    return "\n".join(lines)


def vectors() -> list[tuple[str, bytes]]:
    rng = random.Random(20260927)
    out = [("ctv_msg", MESSAGE)]

    n, e, d = ref.rsa_keygen(2048, rng)
    out.append(("ctv_rsa2048_n", n.to_bytes(256, "big")))
    out.append(("ctv_rsa_e", e.to_bytes(3, "big")))
    out.append(("ctv_rsa2048_pkcs1_sha256",
                ref.rsa_sign_pkcs1(n, d, hashlib.sha256(MESSAGE).digest(), "sha256")))
    salt = bytes(rng.getrandbits(8) for _ in range(32))
    out.append(("ctv_rsa2048_pss_sha256",
                ref.rsa_sign_pss(n, d, hashlib.sha256(MESSAGE).digest(), "sha256", salt)))

    n4, e4, d4 = ref.rsa_keygen(4096, rng)
    out.append(("ctv_rsa4096_n", n4.to_bytes(512, "big")))
    out.append(("ctv_rsa4096_pkcs1_sha384",
                ref.rsa_sign_pkcs1(n4, d4, hashlib.sha384(MESSAGE).digest(), "sha384")))

    for curve, tag, hash_name in ((ref.P256, "p256", "sha256"), (ref.P384, "p384", "sha384"),
                                  (ref.P256, "p256", "sha384")):
        priv = rng.randrange(1, curve.n)
        k = rng.randrange(1, curve.n)
        pub = ref.ec_public(curve, priv)
        sig = ref.ecdsa_sign(curve, priv, hashlib.new(hash_name, MESSAGE).digest(), k)
        out.append((f"ctv_{tag}_{hash_name}_pub", pub))
        out.append((f"ctv_{tag}_{hash_name}_sig", sig))
    return out


def main() -> int:
    parts = [
        "; Generated by tools/gen_cryptotest.py - do not edit.",
        "; Keys and signatures over ctv_msg for the `cryptotest` command.",
        "",
    ]
    parts += [_db(label, data) + "\n" for label, data in vectors()]
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
